[package]
name = "konquer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.7.0"
bevy_common_assets = "0.2.0"
bevy_prototype_lyon = "0.5.0"
glob = "0.3.0"
serde = "1.0.140"
serde_json = "1.0.82"
